[theme]
base = "dark"
primaryColor = "#06b6d4"
backgroundColor = "#05080f"
secondaryBackgroundColor = "#0d121d"
textColor = "#e2e8f0"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
